# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level1BizGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_id', models.CharField(default=1, max_length=10, verbose_name='id')),
                ('bg_name', models.CharField(default='DEFAULT', max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'biz group',
                'verbose_name_plural': 'biz group',
            },
        ),
        migrations.CreateModel(
            name='Level2WorkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wg_id', models.CharField(default=1, max_length=10, verbose_name='id')),
                ('wg_name', models.CharField(default='DEFAULT', max_length=50, unique=True, verbose_name='name')),
                ('bg', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portal.Level1BizGroup', verbose_name='biz group')),
            ],
            options={
                'verbose_name': 'work group',
                'verbose_name_plural': 'work group',
            },
        ),
        migrations.CreateModel(
            name='Level3App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default=1, max_length=10, verbose_name='id')),
                ('app_name', models.CharField(default='DEFAULT', max_length=50, unique=True, verbose_name='name')),
                ('app_ename', models.CharField(default='DEFAULT', max_length=50, unique=True, verbose_name='en name')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='is enabled?')),
                ('wg', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portal.Level2WorkGroup', verbose_name='work group')),
            ],
            options={
                'verbose_name': 'app',
                'verbose_name_plural': 'app',
            },
        ),
        migrations.CreateModel(
            name='Level4AppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='DEFAULT', max_length=50, unique=True, verbose_name='name')),
                ('app', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portal.Level3App', verbose_name='app')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
            },
        ),
        migrations.CreateModel(
            name='Level5AppLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(default='DEFAULT', max_length=50, verbose_name='name')),
                ('link_href', models.CharField(default='#', max_length=200, verbose_name='href')),
                ('link_img', models.CharField(choices=[('icons/analysis.png', 'analysis'), ('icons/bandwidth.png', 'bandwidth'), ('icons/bastion.png', 'bastion'), ('icons/default.svg', 'default'), ('icons/email.png', 'email'), ('icons/it.png', 'it'), ('icons/log.png', 'log'), ('icons/network.png', 'network'), ('icons/nginx.png', 'nginx'), ('icons/oa.png', 'oa'), ('icons/ops.png', 'ops'), ('icons/publish.png', 'publish'), ('icons/security.png', 'security'), ('icons/server.png', 'server'), ('icons/smokeping.png', 'smokeping'), ('icons/statistic.png', 'statistic'), ('icons/tool.png', 'tool'), ('icons/web.png', 'web'), ('icons/wiki.png', 'wiki'), ('icons/zabbix.png', 'zabbix')], default='icons/default.svg', max_length=50, verbose_name='icon')),
                ('link_img_upload', models.ImageField(blank=True, default='', upload_to='icons', verbose_name='custom icon')),
                ('cat', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portal.Level4AppCategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'link',
            },
        ),
    ]
