# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170621_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='level1bizgroup',
            name='bg_rank',
            field=models.IntegerField(default=0, verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='level2workgroup',
            name='added_to_navbar',
            field=models.BooleanField(default=False, verbose_name='added to navbar?'),
        ),
        migrations.AddField(
            model_name='level2workgroup',
            name='wg_rank',
            field=models.IntegerField(default=0, verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='level3app',
            name='app_rank',
            field=models.IntegerField(default=0, verbose_name='rank'),
        ),
    ]
