# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170628_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level5applink',
            name='link_href',
            field=models.CharField(default='#', max_length=500, verbose_name='href'),
        ),
    ]
